import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { Footer } from "@/components";

export const metadata = {
  title: "TechNest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
